// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQyM2bGO3lJAyvQAHWzxrW7P0tXWDyCTI',
    appId: '1:845214120914:web:d487aa0f3854558b70e60b',
    messagingSenderId: '845214120914',
    projectId: 'watchapp-b657c',
    authDomain: 'watchapp-b657c.firebaseapp.com',
    storageBucket: 'watchapp-b657c.firebasestorage.app',
    measurementId: 'G-X2XFEQ1PYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAje-GzIvUjeSuAHI_-fnPIBaQdX3kpsJo',
    appId: '1:845214120914:android:de3c23d763049bbc70e60b',
    messagingSenderId: '845214120914',
    projectId: 'watchapp-b657c',
    storageBucket: 'watchapp-b657c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBadCNejBojbwhLs5h6Pjsl-VPIrc7T-wk',
    appId: '1:845214120914:ios:69450a2b9d61fafa70e60b',
    messagingSenderId: '845214120914',
    projectId: 'watchapp-b657c',
    storageBucket: 'watchapp-b657c.firebasestorage.app',
    iosBundleId: 'com.example.appcounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBadCNejBojbwhLs5h6Pjsl-VPIrc7T-wk',
    appId: '1:845214120914:ios:69450a2b9d61fafa70e60b',
    messagingSenderId: '845214120914',
    projectId: 'watchapp-b657c',
    storageBucket: 'watchapp-b657c.firebasestorage.app',
    iosBundleId: 'com.example.appcounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQyM2bGO3lJAyvQAHWzxrW7P0tXWDyCTI',
    appId: '1:845214120914:web:82999cad236ab93670e60b',
    messagingSenderId: '845214120914',
    projectId: 'watchapp-b657c',
    authDomain: 'watchapp-b657c.firebaseapp.com',
    storageBucket: 'watchapp-b657c.firebasestorage.app',
    measurementId: 'G-VE743DSG3V',
  );
}
